global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.80.175:9100']
  - job_name: 'apache'
    static_configs:
      - targets: ['postgres_exporter:9118']
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
        labels:
          service: 'postgres'
  - job_name: 'bind9'
    static_configs:
      - targets: ['bind_exporter:9119']
